### ISSUE TITLE
help~

### ISSUE THREAD

**Issue by yuzehong1986** [jlararigger/jlr_copy_deformer_weights#1]
Hello, I am Chinese, my English is not good.
Your plugin works great and it helps me a lot.
But for the same cluster, the transfer between different objects is not easy to use and there are errors.
The area of the previous object has a weight of A. After the transfer, the area of the second object has a weight of 1-A. Therefore, if the previous weight value is 0, the weight value will be 1 after the transfer.
So, is there a solution?
Thank you

**Comment by jlararigger** [comment]
Hello,
I tried to reproduce the error by creating a same cluster deformer for two different objects. Then I have edited the weight map of one of them and with the tool I had transfer this weight map to the other object. In all of the tests that I have done, the tool has worked correctly in all of them.
Could you send me an example scene or a step-by-step video to help me to reproduce the error?. With this I'll could see what happens and adjust the plugin as necessary.
